### ISSUE TITLE
Constant assignment

### ISSUE THREAD

**Issue by nanalan** [nanalan/wew#7]
wew won't have variables, per se. All assignments are constant:

```
let foo = false
let foo = true # Mistake
```

**Comment by nanalan** [comment]
Because this syntax requires `let` we can allow `=` to act as `==` in other languages:

```wew
import system.console
let isfact = 1 = 1

console.trace(if isfact then "fact" else "alternative fact")
```

**Comment by BookOwl** [comment]
I think that let should be an expression like 
```
let x = 1 in x + 1
```
This way you would have to use blocks to have variables

**Comment by nanalan** [comment]
@BookOwl Expand? I don't think I understand.

**Comment by BookOwl** [comment]
In most functional languages let is an expression that binds a name to a value in the context of an expression and evaluates to the contained expression.

For example, in Haskell let looks like this:
```haskell
cylinder r h = 
    let sideArea = 2 * pi * r * h  
        topArea = pi * r ^2  
    in  sideArea + 2 * topArea 
```
(http://learnyouahaskell.com/syntax-in-functions)

This defines a function that returns sideArea + 2 * topArea where sideArea = 2 * pi * r * h  and  topArea = pi * r ^2. With let as an expression instead of a statement you don't have to use blocks to use let.

**Comment by nanalan** [comment]
Makes sense.
I'd prefer the following:

```
import math.pi

cylinder(r, h) =>
  sideArea + 2 * topArea
  where sideArea = 2 * pi * r * h,
        topArea = pi * r^2 
```

**Comment by BookOwl** [comment]
I like both
